tuning_problem:
  data: 
  tasks:
    - modules.resource_score.compute_rsm_task_all_regions
    - viz.sunburst.sunburst
  name:  'y'
  target:  'y'
  compute_target: modules.compute_target.compute_runtime
##############################

main:
  tasks:
    - tuning_problem
  arch: PMU_EXAMPLE_FAKE_092be9f8_f19f_11ec_ad61_30d042e819fe
  data_rescale: true
  rsm_iters: 500
  rsm_print: true
  rsm_use_nn_solver: true
  save_sunburst: true
  save_heatmap: true
  save_compat: true
  use_belief: true
  save_raw_line: true
  save_barchart: true
  compat_labels: true
  shorten_event_name: false
  port: 7603
  rsm_cpu_count: 4
