tuning_problem:
    data:  temp.csv
    tasks: 
      - modules.resource_score.compute_rsm_task_all_regions
      # - viz.barchart.create_rsm_error_barchart
      #- viz.barchart.create_rsm_percent_barchart
      - viz.sunburst.sunburst
      #- viz.linechart3.plot_raw_target_values
      #- viz.linechart3.raw_values_per_config
    name:  'ts'
    target:  'y'
    compute_target: modules.compute_target.compute_runtime
##############################

main:
  tasks:
    - tuning_problem
    # - viz.dashboard.dashboard_init

  arch: gptune
  data_rescale: true
  rsm_iters: 500
  rsm_print: true
  rsm_use_nn_solver: true
  save_sunburst: true
  save_heatmap: true
  save_compat: true
  use_belief: true
  save_raw_line: true
  save_barchart: true
  compat_labels: true
  shorten_event_name: false
  port: 7603

